language: node_js
node_js:
  - "14"
jobs:
  include:
    - stage: test
      script:
        - yarn lint
    - stage: release
      if: branch = master
      script:
        - npx semantic-release@15
